/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tiffany.sweet27 (https://sketchfab.com/tiffany.sweet27)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/portal-entrance-v03-1d95bb2dcc0244b28da91e68a3e25a15
title: Portal Entrance V03
*/
//
//
// THIS IS NOT WORKING
//
//

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props: any) {
  const group = useRef()
  // @ts-expect-error
  const { nodes } = useGLTF('scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[0.01, 0.01, 0.01]}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Spheres_Portal_0.geometry}
                material={nodes.Spheres_Portal_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.RedRing_Portal_0.geometry}
                material={nodes.RedRing_Portal_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.BlueRing_6_Portal_0.geometry}
                material={nodes.BlueRing_6_Portal_0.material}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.BlueRing_4_Portal_0.geometry}
                material={nodes.BlueRing_4_Portal_0.material}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.BlueRing_1_Portal_0.geometry}
                material={nodes.BlueRing_1_Portal_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Portal3_Portal_0.geometry}
                material={nodes.Portal3_Portal_0.material}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.BlueRing_2_Portal_0.geometry}
                material={nodes.BlueRing_2_Portal_0.material}
              />
            </group>
            <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.WhiteRing_Portal_0.geometry}
                material={nodes.WhiteRing_Portal_0.material}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.BlueRing_3_Portal_0.geometry}
                material={nodes.BlueRing_3_Portal_0.material}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('scene.gltf')
