/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tiffany.sweet27 (https://sketchfab.com/tiffany.sweet27)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/portal-entrance-v03-1d95bb2dcc0244b28da91e68a3e25a15
title: Portal Entrance V03
*/

//
//
// Generated with npx gltfjsx scene.gltf
//
//
import { useGLTF } from '@react-three/drei'

export function Scene(props: any) {
  // @ts-expect-error
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.01}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Spheres_Portal_0.geometry} material={materials.Portal} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.RedRing_Portal_0.geometry} material={materials.Portal} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.BlueRing_6_Portal_0.geometry} material={materials.Portal} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.BlueRing_4_Portal_0.geometry} material={materials.Portal} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.BlueRing_1_Portal_0.geometry} material={materials.Portal} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Portal3_Portal_0.geometry} material={materials.Portal} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.BlueRing_2_Portal_0.geometry} material={materials.Portal} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.WhiteRing_Portal_0.geometry} material={materials.Portal} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.BlueRing_3_Portal_0.geometry} material={materials.Portal} />
            </group>
          </group>
          {/* <group scale={0.01}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Spheres_Portal_0.geometry} material={materials.Portal}>
                <meshStandardMaterial color="hotpink" transparent />
              </mesh>
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.RedRing_Portal_0.geometry} material={materials.Portal}>
                <meshStandardMaterial color="hotpink" transparent />
              </mesh>
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.BlueRing_6_Portal_0.geometry} material={materials.Portal}>
                <meshStandardMaterial color="hotpink" transparent />
              </mesh>
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.BlueRing_4_Portal_0.geometry} material={materials.Portal}>
                <meshStandardMaterial color="hotpink" transparent />
              </mesh>
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.BlueRing_1_Portal_0.geometry} material={materials.Portal}>
                <meshStandardMaterial color="hotpink" transparent />
              </mesh>
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Portal3_Portal_0.geometry} material={materials.Portal}>
                <meshStandardMaterial color="hotpink" transparent />
              </mesh>
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.BlueRing_2_Portal_0.geometry} material={materials.Portal}>
                <meshStandardMaterial color="hotpink" transparent />
              </mesh>
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.WhiteRing_Portal_0.geometry} material={materials.Portal}>
                <meshStandardMaterial color="hotpink" transparent />
              </mesh>
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.BlueRing_3_Portal_0.geometry} material={materials.Portal}>
                <meshStandardMaterial color="hotpink" transparent />
              </mesh>
            </group>
          </group> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
